### ISSUE TITLE
面试题整理

### ISSUE THREAD

**Issue by AlexZ33** [AlexZ33/lessions#22]
5种方式实现值交换
1. var temp = a; a = b; b = temp; (传统，但需要借助临时变量)
2. a ^= b; b ^= a; a ^= b; (需要两个整数)
3. b = [a, a = b][0] (借助数组)
4. [a, b] = [b, a]; (ES6，解构赋值)
5. a = a + b; b = a - b; a = a - b; (小学奥赛题)
5种方式去掉小数部分
2，3，4种方法是对位进行操作，故数字大小范围限制更大，在 正负2的31次方(2,147,483,648) 之间

1. parseInt(num)
2. ~~num
3. num >> 0
4. num | 0
5. Math.floor(num)  //或ceil等
判断 x 是否是整数
function isInt(x) {
  return (x ^ 0) === x
}
// return Math.round(x) === x
// return (typeof x === 'number') && (x % 1 === 0)
// ES6 -> Number.isInteger()
递归求阶乘
function factorial(n) {
  return (n > 1) ? n * f(n - 1) : n
}
判断符号是否相同
function sameSign(a, b) {
  return (a ^ b) >= 0
}
克隆数组
arr.slice(0)
数组去重
// ES6
Array.from(new Set(arr))

// ES5
arr.filter(function(ele, index, array){
    return index===array.indexOf(ele)
})
数组最大值
function maxArr(arr) {
  return Math.max.apply(null, arr)
}
数组最小值
function minArr(arr) {
  return Math.min.apply(null, arr)
}
随机获取数组的一个成员
function randomOne(arr) {
  return arr[Math.floor(Math.random() * arr.length)]
}
产生随机颜色
function getRandomColor() {
    return `#${Math.random().toString(16).substr(2, 6)}`
}
随机生成指定长度的字符串
function randomStr(n) {
  let standard = 'abcdefghijklmnopqrstuvwxyz9876543210'
  let len = standard.length
  let result = ''

  for (let i = 0; i < n; i++) {
    result += standard.charAt(Math.floor(Math.random() * len))
  }

  return result
}
简易对象的深拷贝
JSON.parse(JSON.stringify(obj))
美化console
console.info("%c哈哈", "color: #3190e8; font-size: 30px; font-family: sans-serif");

**Comment by AlexZ33** [comment]
[这儿有20道大厂面试题等你查收](https://juejin.im/post/5d124a12f265da1b9163a28d?utm_source=gold_browser_extension)
[你要的Vue面试题都在这里](https://juejin.im/post/5d13436f6fb9a07eca698ba0?utm_source=gold_browser_extension)

**Comment by AlexZ33** [comment]
# 数据转换
1、 实现一个函数筛选出客户1290所有的消费数据：即将下面的数据data转换成push输出
![image](https://user-images.githubusercontent.com/21971405/62440715-ead5f500-b783-11e9-84c6-26e2fa600c4d.png)

````
const data = [
    {
        "20181202": [
            {
                "data": "1200",
                "people": "1290"
            },
            {
                "data": "7887",
                "people": "1290"
            }
        ]
    },
    {
        "20190730": [
            {
                "data": "8889",
                "people": "1290"
            },
            {
                "data": "9889",
                "people": "1230"
            }
        ]
    }
]

function dataFormat(data, peopleId) {

 //筛选出客户1290所有的消费数据

}

````

**Comment by AlexZ33** [comment]
答案：
````
function formatData(mydata, peopleId) {
  return mydata.map(item => {
    return {
      time: Object.keys(item)[0],
      data: item[Object.keys(item)[0]].filter(i => i.people)[0].data
    }
  })
}

````

**Comment by AlexZ33** [comment]
# CSS
## 盒模型
* 介绍一下标准的CSS的盒子模型？低版本IE的盒子模型有什么不同的？
（1）有两种， IE 盒子模型、W3C 盒子模型；
（2）盒模型： 内容(content)、填充(padding)、边界(margin)、 边框(border)；
（3）区  别： IE的content部分把 border 和 padding计算了进去;
box-sizing:border-box  包括border、padding、margin
box-sizing:content-box 默认值。不包括border、padding、margin
## BFC
https://blog.csdn.net/sinat_36422236/article/details/88763187
#### BFC是什么
BFC(Block formatting context)直译为"块级格式化上下文"。它是一个独立的渲染区域，只有Block-level box参与， 它规定了内部的Block-level Box如何布局，并且与这个区域外部毫不相干。
如何创建BFC
1、float的值不是none。
2、position的值不是static或者relative。
3、display的值是inline-block、table-cell、flex、table-caption或者inline-flex
4、overflow的值不是visible

#### 利用BFC避免margin重叠。
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>防止margin重叠</title>
</head>
<style>
    *{
        margin: 0;
        padding: 0;
    }
    p {
        color: #f55;
        background: yellow;
        width: 200px;
        line-height: 100px;
        text-align:center;
        margin: 30px;
    }
    div{
        overflow: hidden; /* 为了构造成两个BFC，这样margin就不会重叠了*/
    }
</style>
<body>
    <p>看看我的 margin是多少</p>
    <div>
        <p>看看我的 margin是多少</p>
    </div>
</body>
</html>
```
#### 解决float重叠
为了解决float浮动重叠，BFC的区域不会与float box重叠。
所以我们让right单独成为一个BFC
```css
 .right {
        overflow: hidden;
        height: 300px;
        background: rgb(170, 54, 236);
        text-align: center;
        line-height: 300px;
        font-size: 40px;
    }
```
#### 清除浮动
计算BFC的高度时，浮动元素也参与计算。
```css
.par {
      border: 5px solid rgb(91, 243, 30);
      width: 300px;
      overflow: hidden;
}
    
.child {
    border: 5px solid rgb(233, 250, 84);
    width:100px;
    height: 100px;
    float: left;
}
```

## 水平垂直居中
### 行内元素
```css
CSS设置行内元素的垂直居中

div{height:30px; line-height:30px} /*DIV内的行内元素均会垂直居中*/ 
 

PS:当然，如果既要水平居中又要垂直居中，那么综合一下

div{text-align:center; height:30px; line-height:30px} 

垂直居中：vertical-align: middle;
水平居中：text-align:center;
```
### 块级元素
https://github.com/hawx1993/tech-blog/issues/12
```
*  水平居中：
        * 用margin：子：width；margin：0 auto；
        * 用test-align：父：text-align:center;子：display:inline-block;
        * 用transform：父：relative；子：absolute；transform:translate(-50%);
        * 用Table：父：display:table;margin:0 auto;
        * 用flex：父：flex；justify-content:center;
        * 用flex——2：父：flex；子：margin:0 auto;

* 垂直居中：
        * 用vertical-align:
        父：vertical-align:middle;display:table-cell;height:20px;只有一个元素是inline或者inline-block或者table-cell时vertical-align才管用。
        * 用vertical-align：父：vertical-align：middle；display：inline-block;line-height：20px；
        * 用transform：父：relative；子：absolute；transform:translate(0,-50%);
        * 用flex：父：flex；align-item:center;

* 水平垂直居中：
        * 1)利用vertical-align,text-align,inline-block实现
        .parent{display:table-cell;vertical-align:middle;text-align:center;height:100px}
        .child{display:inline-block;}

        * 2) transform
        .parent{position:relative;}
        .child{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);}
        
        * 3)利用flex实现
         .parent{display:flex;justify-content:center;align-items:center;}
```

## 两列、三列布局
两列：
方法1.浮动布局 左:固定宽度+左浮动; 右:margin-left:左侧宽度。
方法2:浮动布局—+负外边距 左:固定宽度+左浮动+margin-right:-100%; ⽗父(右):左浮动+width:100%; 右:margin-left:左宽度。
三列：
中间⾃自适应，两边固定宽度
1.绝对定位加margin留空 左、右⽤用绝对定位在左右两侧，中间栏利利⽤用margin-left和margin-right
2.浮动+负外边距(太复杂放弃) 
3.浮动定位法(中间栏也不不是等⾼高) 中间栏:放最后+margin-left:左侧宽+margin-right:右侧宽。 左:左浮动;
右:浮动;
```css
 <!--左右侧栏的位置可以更更改--> 
 <div id="left"></div> 
 <div id="right"></div> 
 <!--中间栏放最后-->
<div id="main"></div>
*{
  margin:0;
  padding:0;
  height:100%;
} 
#left{
  width:300px;
  background-color:yellow;
  float:left;
} 
#right{
  width:200px;
  background-color:orange;
  float:right;
} 
#main{
  background-color:aqua;
  margin-left:300px;
  margin-right:200px;
}
```
4 flexbox
```css
 #box{
            height: 500px;
            padding: 0;
            margin: 0;
            display: flex;
}
        #left{
            background: yellow;
            order: 1;
            flex: 20%;
} #content{
            flex:3 1 60%;
            background: blue;
            order: 2;
} #right{
            flex: 20%;
            background: red;
            order: 3;
}
```

两栏等高
1 左浮动+margin-bottom和padding-bottom
2 table-row加table-cell
3 flex (width不不起作⽤用的。)
## 移动端适配（css函数）
查看桌面文件
rem  meta scale=1/dpr font-size 
vw
vw+rem
## 1px问题
从第一部分的讨论可知 viewport 的 initial-scale 具有缩放页面的效果。对于 dpr=2 的屏幕，1px压缩一半便可与1px的设备像素比匹配，这就可以通过将缩放比 initial-scale 设置为 0.5=1/2 而实现。以此类推 dpr=3的屏幕可以将 initial-scale设置为 0.33=1/3 来实现。

## 动画
@keyframe:https://www.runoob.com/cssref/css3-pr-animation-keyframes.html
transition: https://www.runoob.com/cssref/css3-pr-transition.html
transform、transition和animation 三者的区别：http://www.divcss5.com/css3-style/c57157.shtml
## css3特性 
#### @function () {
  @return ....
}

#### 继承样式 @
```css
@mixin textrow($row : 1) {
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: $row;
  -webkit-box-orient: vertical;
}
```
## flex: 0 1 auto是什么意思
首先明确一点是， flex 是 flex-grow、flex-shrink、flex-basis的缩写。

flex-grow属性定义项目的放大比例，默认为0，即如果存在剩余空间，也不放大。

flex-shrink属性定义了项目的缩小比例，默认为1，即如果空间不足，该项目将缩小。

flex-basis属性定义了在分配多余空间之前，项目占据的主轴空间（main size）。浏览器根据这个属性，计算主轴是否有多余空间。它的默认值为auto，即项目的本来大小。


## 回流重绘
https://github.com/Advanced-Frontend/Daily-Interview-Question/issues/24
